package com.zack.mapper;

import com.zack.model.ProductCart;
import com.zack.model.ProductCartExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.cglib.core.ProcessArrayCallback;

public interface ProductCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_cart
     *
     * @mbggenerated
     */
    int countByExample(ProductCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_cart
     *
     * @mbggenerated
     */
    int deleteByExample(ProductCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_cart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_cart
     *
     * @mbggenerated
     */
    int insert(ProductCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_cart
     *
     * @mbggenerated
     */
    int insertSelective(ProductCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_cart
     *
     * @mbggenerated
     */
    List<ProductCart> selectByExample(ProductCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_cart
     *
     * @mbggenerated
     */
    ProductCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_cart
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductCart record, @Param("example") ProductCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_cart
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductCart record, @Param("example") ProductCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductCart record);

    ProductCart selectCartByUserIdAndProductId(@Param("uid") Integer uid, @Param("productId") Integer productId);

    List<ProductCart> selectCartByUserId(Integer uid);

    int selectCartProductCheckedStatusByUserId(Integer uid);

    int deleteByUserIdProductIds(@Param("uid") Integer uid, @Param("productList") List<String> productList);

    int checkedOrUncheckedProduct(@Param("uid") Integer uid, @Param("productId") Integer productId, @Param("checked") int checked);

    int selectCartProductCount(Integer uid);

    List<ProductCart> selectCheckedCartByUserId(Integer uid);
}