package com.zack.mapper;

import com.zack.model.ProductOrder;
import com.zack.model.ProductOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    int countByExample(ProductOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    int deleteByExample(ProductOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    int insert(ProductOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    int insertSelective(ProductOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    List<ProductOrder> selectByExample(ProductOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    ProductOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductOrder record, @Param("example") ProductOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductOrder record, @Param("example") ProductOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductOrder record);
}