package com.zack.mapper;

import com.zack.model.ProductPayInfo;
import com.zack.model.ProductPayInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductPayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pay_info
     *
     * @mbggenerated
     */
    int countByExample(ProductPayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pay_info
     *
     * @mbggenerated
     */
    int deleteByExample(ProductPayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pay_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pay_info
     *
     * @mbggenerated
     */
    int insert(ProductPayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pay_info
     *
     * @mbggenerated
     */
    int insertSelective(ProductPayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pay_info
     *
     * @mbggenerated
     */
    List<ProductPayInfo> selectByExample(ProductPayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pay_info
     *
     * @mbggenerated
     */
    ProductPayInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pay_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductPayInfo record, @Param("example") ProductPayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pay_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductPayInfo record, @Param("example") ProductPayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pay_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductPayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pay_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductPayInfo record);
}